name: Weekly biz task

on:
  # 11:00 UTC every Monday ⇒ 05:00 US-Central during DST*
  schedule:
    - cron: '0 11 * * MON'
  # lets you trigger it manually from the Actions tab
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        ZAPIER_MCP_URL: ${{ secrets.ZAPIER_MCP_URL }}
        ZAPIER_MCP_TOKEN: ${{ secrets.ZAPIER_MCP_TOKEN }}
        ZAPIER_MCP_SERVER_URL: ${{ secrets.ZAPIER_MCP_SERVER_URL }}
        PERSONAL_EMAIL: ${{ secrets.PERSONAL_EMAIL }}
    steps:
    - uses: actions/checkout@v4            # grab your code
    - name: Set up Python
      uses: actions/setup-python@v5        # latest stable action 
      with:
        python-version: '3.12'
        cache: 'pip'                       # speeds up installs on reruns
    - name: Install deps
      run: pip install -r requirements.txt
    - name: Run script
      run: python src/week-3/responses-api/workflow.py